### ISSUE TITLE
Document how to refresh the server when files change

### ISSUE THREAD

**Issue by tkrotoff** [jasmine/gulp-jasmine-browser#12]
A common pattern is to serve the updated files when they change. How can this be achieved?

It would be also nice to document inside README.md that the server is running on port 8888 by default and how to change it (I had to read the source code to get this info).

**Comment by charleshansen** [comment]
Added port documentation in 7fdebe644e2e8ba5b6b2a3d1aa06e42ab9dae61d

I'm pretty sure gulp.watch can be used if you want to watch file changes if you want something basic. We should add an example. We always use Webpack for the file watching for what it is worth.

**Comment by charleshansen** [comment]
Added watch documentation 3ea4d17c0e32096f800ff80ce41d38d697af420b

**Comment by tkrotoff** [comment]
Thx!
