### ISSUE TITLE
Ability to serve images and font files

### ISSUE THREAD

**Issue by runemadsen** [jasmine/gulp-jasmine-browser#19]
Often my tests involve making Ajax request to load an image or a font. It would be great to have the ability to serve these type of files on the test server, so I can load them like this `localhost:8888/myfile.jpg'.

Right now, this doesn't seem possible?

**Comment by rdy** [comment]
I'd be glad to take a pull request to do this if you'd like this feature. It currently will attempt to serve javascript and css files only at the moment.
