### ISSUE TITLE
How to set a reporter?

### ISSUE THREAD

**Issue by bartspedden** [jasmine/gulp-jasmine-browser#21]
I'm trying to set a jasmine reporter (JUnitXmlReporter) so that I can use jenkins to report on tests.

The following did not work:

```javascript
const jasmineBrowser = require('gulp-jasmine-browser');
const reporters = require('jasmine-reporters');
const junitReporter = new reporters.JUnitXmlReporter({
          savePath: 'dist',
          consolidateAll: false
});

gulp.task('jasmine-phantom', function() {
  return gulp.src(['dist/lq-cctlib-client.js', 'test/mocha_phantom_test.js']) 
    .pipe(jasmineBrowser.specRunner({
        console: true,
        integration:true,
        reporter: junitReporter
    }))
    .pipe(jasmineBrowser.headless());
});
```

What is the correct way to set a different reporter for gulp-jasmine-browser?

**Comment by charleshansen** [comment]
We don't support this right now unfortunately. Supporting other reporters is surprisingly hard. This issue is similar to #13 is you want some more context.

**Comment by rdy** [comment]
We'd love to take a pull request if you need this feature, right now, for the moment it hasn't come up as a priority yet.
