### ISSUE TITLE
Unable to destroy or restart the server

### ISSUE THREAD

**Issue by GSchutz** [jasmine/gulp-jasmine-browser#24]
I have a task like this:
```
...
var server;

gulp.task('jasmine', ['dist'], function() {
  gulp.src(SPECS)
    .pipe(watch(SPECS))
    .pipe(jasmineBrowser.specRunner())
    .pipe(server = jasmineBrowser.server({port: 7007}));
});

gulp.task('another', function() {
  if (server) {
    server.destroy();
    server.end();
  }
});
```

and I'm trying to destroy the server by a method `server.destroy()` returned by the `jasmineBrowser.server` method. But the `destroy` and `end` method seems to do nothing.

Any idea?

**Comment by rdy** [comment]
The problem I'm seeing is that you if you are using something like gulp-watch (I'm presuming from the example you've given), that creates a stream that doesn't close. The result returned by jasmineBrowser server is a stream. The end and destroy methods are for that stream which does not end. Ending  the stream does not kill the server when it is in a watching mode. The end of the stream currently indicates the point at which to build and run the tests, it isn't used for killing the server.

The easiest way to do what it looks like you are trying to do is use something like lsof to find the process of the thing running on port 7007 and killing that.

Anyways, I don't think we plan on adding extra behaviors to the express server based on manipulating the stream passing through it. It doesn't return the server object so you shouldn't expect that to kill the server.

**Comment by GSchutz** [comment]
Yes @rdy.

That's it. So I build a module for this ([gulp-restart](https://github.com/GSchutz/gulp-restart)), and maybe you could check out.
It's my first experience with standard streams, so I don't know if is the best approach. I used the child_process `spaw` method because the lsof would be too much specific.

Thanks.
