### ISSUE TITLE
New files are not added until jasmine is restarted

### ISSUE THREAD

**Issue by Gerg** [jasmine/gulp-jasmine-browser#25]
If I create a new spec file, I would expect it to show up without having to restart jasmine. 

You should re-glob all the files every time I load the page. This is how superior jasmine runners like [Jasmine-Py](https://github.com/jasmine/jasmine-py) detect new files.

If you really care about performance, you can only actually re-render the page when the glob has changed. 

STRONG WORDS!

**Comment by rdy** [comment]
I believe this is due to the use of gulp < 4, which should change once they change their globbing strategy (you can use the unreleased version which has existed for a year or more). @charleshansen let me know if you disagree but I don't this this is a part of what this gulp plugin does.

**Comment by charleshansen** [comment]
@rdy: Agreed. I think Greg's suggestion of reglobbing on every request is technically possible, but would require changing a ton of stuff. Better to wait for gulp 4.
