### ISSUE TITLE
How to get it to not print the full stack trace on errors in console mode

### ISSUE THREAD

**Issue by gwynjudd** [jasmine/gulp-jasmine-browser#29]
I think that the stack trace is useful, but most of the time, seeing the full stack trace is producing a lot of clutter. For example, with the stack trace:

![image](https://cloud.githubusercontent.com/assets/314188/15278134/3a2ffac6-1b68-11e6-9bc7-5e1733d84e19.png)

(Goes on for about 50 lines of stuff not related to the functionality under test).

I found it more useful to comment out this line (https://github.com/jasmine/gulp-jasmine-browser/blob/master/src/lib/console.js#L145), to produce the output:

![image](https://cloud.githubusercontent.com/assets/314188/15278151/78c0eb56-1b68-11e6-9518-aaa51350ca81.png)

My gulpfile:

```
var jasmineBrowser = require('gulp-jasmine-browser');
gulp.task('test', function () {
	gulp.src([
		'core/core_vendor_bundle.js',
		'core/core_bundle.js',
		'core/typescript/all.js',
		'core/vendor/date-en-US.js',
		'secure/core/typescript/all.js',
		'secure/core/core_app_bundle.js',
		'secure/app/bower_components/lorem/src/library/lorem.js',

		'secure/app/view_unit_tests/automated_test_cases/ut_globals.js'])

		.pipe(jasmineBrowser.specRunner({ console: true }))
		.pipe(jasmineBrowser.headless());
});
```

I don't mind submitting a PR, but I can't see any obvious way to add a configuration option for the console reporter. Any hints?

**Comment by rdy** [comment]
I think the right way to do this is to create an option in the headless runner to control stderr, allow the user to redirect it to '/dev/null' for example.

The console reporter would need to be modified to write stacktrace errors to stderr. Also the phantom and slimer runners would need to handle writing the output of stderr to the test runner processes stderr.

I'd be willing to take a pull request on this, and I might eventually just get to supporting this if I have time.

**Comment by deckar01** [comment]
The trace is 90% async event indirection from the loading logic, 9% jasmine internals, and 1% user specs. It would be nice if only the user specs were output and if it had a more useful mapping to the original file.

I believe the main jasmine reporter tries to filter jasmine internals from the stack trace, but there is not much it can do when there is external instrumentation below it in the call chain.

**Comment by rdy** [comment]
You can bring your own reporter to the table so this can be implemented using a custom reporter.

**Comment by whyboris** [comment]
I wrote a reporter last year that only shows you the line containing the file you've written, and excludes all the irrelevant stack trace information: https://github.com/whyboris/karma-helpful-reporter

Hope you find it useful 😀

**Comment by slackersoft** [comment]
Jasmine 3.0 will also elide lines from Jasmine-Core in an effort to only show lines of the stack trace that are relevant to the suite. Hopefully this helps with this issue going forward.
