### ISSUE TITLE
Support proxy to the call to phantom cli

### ISSUE THREAD

**Issue by purpleD17** [jasmine/gulp-jasmine-browser#31]
I need phantom to support a proxy. I drilled down into my setup and figured out this https://github.com/jasmine/gulp-jasmine-browser/blob/master/src/lib/headless.js#L47 can be changed to:

```
  const phantomProcess = spawn(command, ['--proxy=http://myproxy.com:80', runner, port, query], {cwd: path.resolve(__dirname), stdio: 'pipe'});
```

But obviously this would need to come down as one of the options

**Comment by rdy** [comment]
Sure we could add this pretty easily.

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
