### ISSUE TITLE
headless tests fails silently when portfinder returns an error

### ISSUE THREAD

**Issue by atomanyih** [jasmine/gulp-jasmine-browser#34]
hi peeps

we're having an issue on circleci through `pui-react-tools` where we try to run our tests, but the server never starts, the tests never run and the task returns exit code 0

we dug in a bit and figured out that portfinder is erroring with:

```
{ [Error: listen EADDRNOTAVAIL]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen' }
```

at https://github.com/jasmine/gulp-jasmine-browser/blob/master/src/lib/headless.js#L26

this may be related to: https://github.com/indexzero/node-portfinder/issues/34

in any case, it would be nice if `gulp-jasmine-browser` errored out or printed something to the user

@clairethompson

**Comment by eriktrom** [comment]
Portfinder has been updated but not pushed to npm. I will push it when I get a some positive verification that its working. 

Let me know if using `portfinder@1.0.7-beta.0` in you package.json fixes the issue and if not throw me a stack trace.

thanks a bunch in advance

**Comment by eriktrom** [comment]
I should have read the whole issue - if this issue is with circle ci no need to try and verify (unless you have time) - the ember-cli team is going to give it a good test run - after which I'll publish and circle ci should 'just work'

**Comment by rdy** [comment]
I bumped the dependency, if the issue persists feel free to reopen.
