### ISSUE TITLE
Reporter jsunit

### ISSUE THREAD

**Issue by edgehero** [jasmine/gulp-jasmine-browser#40]
Currently i trying to run jasmine-browser with JUnitXmlReporter
It gives no problems when there are no errors.
but when it should give back an error it gives a jasmine reporter error:

```
[16:29:44] Starting 'build-unit-test'...
[16:29:44] Jasmine server listening on port 8000
/vagrant/node_modules/jasmine-reporters/src/junit_reporter.js:274
            if (isFailed(spec)) { spec._suite._failures += spec.failedExpectations.length; }
                                             ^

TypeError: Cannot read property '_failures' of undefined
```

what am i doing wrong? 
My gulp code i use is:
(junit reporter is from npm jasmine-reporters )

```
gulp.task('build-unit-test', function() {
    return gulp.src(testscripts)
        .pipe(concat('all.js'))
        .pipe(jasmineBrowser.specRunner({console: true}))
        .pipe(jasmineBrowser.headless({
            throwFailures: false,
            reporter: new reporters.JUnitXmlReporter({savePath: buildpath, consolidateAll: false, filePrefix: 'jsunit'})
        }))
});
```

**Comment by rdy** [comment]
Have you tried any of the other reporters in the package? I recall seeing an issue with the jUnitReporter not producing the expected output that jasmine 2 expects. I think it is an issue with the reporter rather than something you are doing wrong.

If you can put together a simple test case I'd be happy to look into the issue and potentially fix it in the reporter or in the code for gulp-jasmine-browser. 

I'm following the spec of the custom reporter as described by the jasmine documentation here:
http://jasmine.github.io/2.5/custom_reporter.html

**Comment by edgehero** [comment]
Thanks for the fast responds, i put a simple test together for you 

https://github.com/edgehero/jasmine-testcase

Setup: 
Npm install ( to install gulp and the correct npm packages ) 
gulp teamcity (test of reporter that works correctly with gulp-jasmine-browser )
gulp junit (same test but junit reporter, this gives errors and the bug)

**Comment by edgehero** [comment]
Did you find a reason why its failing?

**Comment by Martin1982** [comment]
I'm having the same trouble; I get perfect reports when all tests succeed. But when one fails (and where I'd need the reports the most) I get the error mentioned by @edgehero

**Comment by PouleR** [comment]
Would be great if there's a fix available for this issue, the error comes however from the junit_reporter.js file (from jasmine-reporters repo). The example by @edgehero is excellent to reproduce the issue.

**Comment by slackersoft** [comment]
It sounds like this issue originates from [jasmine-reporters](https://github.com/larrymyers/jasmine-reporters) and not from Jasmine or gulp-jasmine-browser itself, so I'm going to close this.

Thanks for using Jasmine!
