### ISSUE TITLE
Enable verbose logging

### ISSUE THREAD

**Issue by DavePilks** [jasmine/gulp-jasmine-browser#49]
There does not seem to be an option to enable verbose logging so that we can see spec names instead of progress dots. Is this something that is missing for was it intentionally left out?

**Comment by slackersoft** [comment]
Jasmine doesn't have a built-in console reporter with full spec descriptions. You might check out [jasmine-reporters](https://github.com/larrymyers/jasmine-reporters) for a range of various other reporters that other members of the community have written.

Hope this helps. Thanks for using Jasmine!

**Comment by rdy** [comment]
It is possible to specify or build your own reporters to do this. Check out the reporters mentioned.
