### ISSUE TITLE
Windows: Can't run gulp-jasmine-browser with Headless Chrome.

### ISSUE THREAD

**Issue by kresli** [jasmine/gulp-jasmine-browser#57]
My apologies to create a new issue which is similar to https://github.com/jasmine/gulp-jasmine-browser/issues/52, however I believe this happening on windows.

Pasted from [52](https://github.com/jasmine/gulp-jasmine-browser/issues/52)

hit on the same issue using `"gulp-jasmine-browser": "^3.0.1",`, `"gulp": "^4.0.0",`
```
 Error: spawn C:\Users\Ed\test module\node_modules\gulp-jasmine-browser\lib\runners\chrome_runner ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

```
gulp.src(options.files)
                .pipe(jasmineBrowser.specRunner({
                    console: true
                }))
                .pipe(jasmineBrowser.headless({
                    driver: 'chrome',
                }))
```

BTW, I'm on windows 10 so it could be a path issue in spawn process?

I think this could be related to the issue https://github.com/nodejs/node/issues/7367#issuecomment-229721296

**Comment by rdy** [comment]
Yes, this seems to be a node spawn issue. I don't happen to have the right environment to look into the problem right this moment. I'd appreciate the pull request if you wanted to attempt a fix.

**Comment by kresli** [comment]
I tried back then, but none of my tests executed, however that doesn't mean shell option didn't fix the issue. Unfortunately we are moving away from gulp so not really sure I'll be able to test it.  However I tried to clone your repo and run tests but my screen just flashed with errors starting from missing JAVA even I'm sure I have it installed.  If I'll have a spare time I'll try to fix it, but as I said, because we are moving away from gulp, I doubt it. 
PS: maybe docker would help here?

**Comment by rdy** [comment]
It uses selenium in the test suite to launch a browser but it may not be able to find a jdk. You can run without those tests that launch selenium, I’m not sure why it wouldn’t be available. Anyways you can try without those tests, Travis can’t run those anyways because of permissions issues. There should be an environment variable you can set to emulate travis chi which should exclude selenium.

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
