### ISSUE TITLE
Is there any way to print console error from the headless Chrome?

### ISSUE THREAD

**Issue by brookhong** [jasmine/gulp-jasmine-browser#58]
For example, I created a gulp task to test my chrome extension, to load content_scripts as below:

    gulp.task('test', function () {
        return gulp.src(['content_scripts/**/*.js', 'tests/*.spec.js'])
            .pipe(jasmineBrowser.specRunner({console: true}))
            .pipe(jasmineBrowser.headless({driver: 'chrome'}));
    });

I know there must be some console errors from the headless browser to load content_scripts without loading some other lib, but how to get the console error inside headless chrome printed out on my shell of running gulp?

**Comment by rdy** [comment]
it should print console.log right now, it could probably be extended to console.error and console.warn as well.

**Comment by cancerberoSgx** [comment]
@rdy it's not :( using puppeteer
