### ISSUE TITLE
Using headless Chrome (Puppeteer), no specs found in CI

### ISSUE THREAD

**Issue by reid47** [jasmine/gulp-jasmine-browser#59]
We are using `pui-react-tools` verison 4.0.1, which uses `gulp-jasmine-browser` version 3.0.2. We have installed `puppeteer` version 1.4.0. We can run the tests locally from the command line (in headless mode), but when run in our CI environment, we see this:

```
[23:07:32] Starting 'specAppRun'...
[23:07:49] Jasmine server listening on port 8888

undefined specs, 0 failures
Finished in NaN seconds
[23:07:50] Finished 'specAppRun' after 18 s
```

My Jasmine.install config:

```
Jasmine.install({
  headlessServerOptions: {
    includeStackTrace: true,
    random: false,
    isVerbose: false,
    port: 8888,
    driver: 'chrome'
  },
  appGlobs: ['./spec/pivotal-ui-react/**/*_spec.js'],
  headlessSpecRunnerOptions: {profile: true},
  webpack: {test: () => testWebpack}
});
```

Is this a known problem? Is there something more we should do?

**Comment by rdy** [comment]
What version of jasmine core is being added? I think that the latest jasmine might be broken. If you lock down to 2.99 it might work.

**Comment by reid47** [comment]
@rdy We figured out what was going wrong: we didn't have Chrome installed on CI, so we were using the default Chromium that comes with Puppeteer. Seems not to work. Just FYI, but we'll close this issue.
