### ISSUE TITLE
Tests do not always reflect the latest version of spec file

### ISSUE THREAD

**Issue by charleshansen** [jasmine/gulp-jasmine-browser#6]
There is a small gap between when the files change and the server serves the up-to-date files. We should be able to wait until the files are finished being built, like in Jasmine Gem (because of Sprockets).

The goal should be that old (no longer accurate) test runs are never shown to the developer.

**Comment by charleshansen** [comment]
Fixed for Webpack as part of 88c1675b0aba19bfb3e7707543e735f6bb29323b
Browserify solution will be more complicated

**Comment by rdy** [comment]
Closing this issue for the webpack solution, we can take a pull request for someone who has a browserify pipeline.
