### ISSUE TITLE
Auto refresh not working

### ISSUE THREAD

**Issue by Migacz85** [jasmine/gulp-jasmine-browser#60]
Using following code from docs example did not refresh the jasmine tests:

var gulp = require('gulp');
var jasmineBrowser = require('gulp-jasmine-browser');
var watch = require('gulp-watch');

gulp.task('jasmine', function() {
  var filesForTest = ['src/**/*.js', 'spec/**/*_spec.js'];
  return gulp.src(filesForTest)
    .pipe(watch(filesForTest))
    .pipe(jasmineBrowser.specRunner())
    .pipe(jasmineBrowser.server({port: 8888}));
});

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
