### ISSUE TITLE
fdescribe and fit should exit with code different than 0

### ISSUE THREAD

**Issue by cancerberoSgx** [jasmine/gulp-jasmine-browser#64]
if i use `fdescribe()` or `fit()` in my specs then I expect that the process `gulp jasmine` exit with status code different than zero as jasmine CLI tool currently does.  (test should fail no matter if report is green because I forgot to remove those callse). 

Since there's no error to catch from gulp I need `gulp-jasmine-browser` to throw in that case too, perhaps not printing any stacktrace and just a message, as the jasmine CLI currently does.

thanks

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
