### ISSUE TITLE
Serve .js files as static assets but don't load them

### ISSUE THREAD

**Issue by cancerberoSgx** [jasmine/gulp-jasmine-browser#68]
Just that, I need to load some .js scripts programmatically and I need them to be on the same path as the main html file But in this case is important that the scripts don't load automatically. It seems that the html file will load any *.js assets automatically. 
My use case is an application loading a webworker from a custom place and the loading bits need to be done programatically using loadScripts() webworker API to support custom domains. I can't find a way to instruct this framework to just serve .js without load them. Any tip is very appreciated. Thanks, keep it up!

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
