### ISSUE TITLE
Support for stopping a spec on expectation failure

### ISSUE THREAD

**Issue by slackersoft** [jasmine/gulp-jasmine-browser#7]
Jasmine 2.3 is introducing the ability to stop the execution of a spec when an expectation fails, similar to what happens if an Error is thrown. A user should be able to configure the `phantomjs` function to enable this feature. [Tracker story for the core feature](https://www.pivotaltracker.com/n/projects/10606/stories/1165916). This should cause the phantom_runner to add a query param `throwFailures=true` when loading the page.

**Comment by charleshansen** [comment]
Done, also supporting `random` and `catch` options
