### ISSUE TITLE
How to integrate fixtures (JSON files)?

### ISSUE THREAD

**Issue by tkrotoff** [jasmine/gulp-jasmine-browser#9]
gulpfile.js:

```JavaScript
gulp.task('jasmine', function() {
  return gulp.src(
    [
      'node_modules/underscore/underscore.js',
      'node_modules/angular/angular.js',
      'node_modules/angular-mocks/angular-mocks.js',
      '.tmp/app/all.js',
      '.tmp/test/unit/all.js',
      'test/*.json'  // <====
    ],
    { base: '.' }
  )
    .pipe($.jasmineBrowser.specRunner())
    .pipe($.jasmineBrowser.server());
});
```

See the `test/*.json` => those are JSON files that I load via XHR inside my unit tests. With gulp-jasmine-browser they don't get loaded and the XHR requests return 404 inside localhost:8888.

Using Karma, you can do that (see http://karma-runner.github.io/0.12/config/files.html):

```JavaScript
module.exports = function(config) {
  config.set({
    basePath: '',

    frameworks: ['jasmine'],

    files: [
      // Source dependencies
      'node_modules/underscore/underscore.js',
      'node_modules/angular/angular.js',

      // Spec dependencies
      'node_modules/angular-mocks/angular-mocks.js',

      // Source files
      '.tmp/app/all.js',

      // Spec files
      '.tmp/test/unit/all.js',

      // Fixtures
      {
        pattern: 'test/*.json',
        included: false
      }
    ],

    ...
  });
};
```

And XHR the JSON files will work.

**Comment by slackersoft** [comment]
Jasmine does not have built-in support for fixtures or ajax mocking. The jasmine team maintains [jasmine-ajax](https://github.com/jasmine/jasmine-ajax) to serve the latter need, but providing the response is left up to the user.

**Comment by tkrotoff** [comment]
After some more investigations, JSON files get loaded on the server created by gulp-jasmine-browser. It was just a problem of path that got me into 404s. Sorry for the bad report.
